#version: '3.8'

networks:
  xxxx-companyname:
    external: true  # Indicamos que la red ya existe externamente y no la recreamos

services:
  frontend:
    image: frontend-react  # Aquí defines el nombre de la imagen
    build:
      context: .
      dockerfile: DOCKERFILE  # Asegúrate de que el nombre de tu Dockerfile esté bien especificado
    container_name: xxxx-companyname-frontend
    ports:
      - "3001:3000"  # Exponemos el puerto 3001 en el host para acceder al frontend de React
    networks:
      - xxxx-companyname
    restart: always